services:
  db:
    image: postgres:15-alpine
    environment:
      # Read variables from the .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env  # <-- This tells Docker Compose to load the .env file
    depends_on:
      - db

volumes:
  postgres_data: